### ISSUE TITLE
Cross release on open marketplace

### ISSUE THREAD

**Issue by basxto** [spnda/VSC-NML#3]
Please also make this extension available through [Eclipse Open VSX Registry](https://open-vsx.org/) for [VSCodium](https://vscodium.com/).

The [publishing process](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension) is said to be similar to the one from Microsoft's Visual Studio Marketplace.

**Comment by spnda** [comment]
Hi, thank you for your suggestion. I have just gone ahead and published the package on the [OpenVSX Registry](https://open-vsx.org/extension/spnda/nml-language). I hope it works!
